=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

The version of the OpenAPI document: 1.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RubyEveesiClient::GetCorporationsCorporationIdContractsContractIdBids200Ok
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RubyEveesiClient::GetCorporationsCorporationIdContractsContractIdBids200Ok do
  let(:instance) { RubyEveesiClient::GetCorporationsCorporationIdContractsContractIdBids200Ok.new }

  describe 'test an instance of GetCorporationsCorporationIdContractsContractIdBids200Ok' do
    it 'should create an instance of GetCorporationsCorporationIdContractsContractIdBids200Ok' do
      expect(instance).to be_instance_of(RubyEveesiClient::GetCorporationsCorporationIdContractsContractIdBids200Ok)
    end
  end
  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "bid_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "bidder_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "date_bid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
