=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

The version of the OpenAPI document: 1.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RubyEveesiClient::GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RubyEveesiClient::GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails do
  let(:instance) { RubyEveesiClient::GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails.new }

  describe 'test an instance of GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails' do
    it 'should create an instance of GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails' do
      expect(instance).to be_instance_of(RubyEveesiClient::GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails)
    end
  end
  describe 'test attribute "cycle_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "head_radius"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "heads"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "product_type_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "qty_per_cycle"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
