=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

The version of the OpenAPI document: 1.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RubyEveesiClient::PostCharactersCharacterIdAssetsLocations200Ok
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RubyEveesiClient::PostCharactersCharacterIdAssetsLocations200Ok do
  let(:instance) { RubyEveesiClient::PostCharactersCharacterIdAssetsLocations200Ok.new }

  describe 'test an instance of PostCharactersCharacterIdAssetsLocations200Ok' do
    it 'should create an instance of PostCharactersCharacterIdAssetsLocations200Ok' do
      expect(instance).to be_instance_of(RubyEveesiClient::PostCharactersCharacterIdAssetsLocations200Ok)
    end
  end
  describe 'test attribute "item_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "position"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
