=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

The version of the OpenAPI document: 1.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RubyEveesiClient::PostCharactersCharacterIdMailRecipient
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RubyEveesiClient::PostCharactersCharacterIdMailRecipient do
  let(:instance) { RubyEveesiClient::PostCharactersCharacterIdMailRecipient.new }

  describe 'test an instance of PostCharactersCharacterIdMailRecipient' do
    it 'should create an instance of PostCharactersCharacterIdMailRecipient' do
      expect(instance).to be_instance_of(RubyEveesiClient::PostCharactersCharacterIdMailRecipient)
    end
  end
  describe 'test attribute "recipient_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "recipient_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["alliance", "character", "corporation", "mailing_list"])
      # validator.allowable_values.each do |value|
      #   expect { instance.recipient_type = value }.not_to raise_error
      # end
    end
  end

end
