=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

The version of the OpenAPI document: 1.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RubyEveesiClient::PutFleetsFleetIdSquadsSquadIdNotFound
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RubyEveesiClient::PutFleetsFleetIdSquadsSquadIdNotFound do
  let(:instance) { RubyEveesiClient::PutFleetsFleetIdSquadsSquadIdNotFound.new }

  describe 'test an instance of PutFleetsFleetIdSquadsSquadIdNotFound' do
    it 'should create an instance of PutFleetsFleetIdSquadsSquadIdNotFound' do
      expect(instance).to be_instance_of(RubyEveesiClient::PutFleetsFleetIdSquadsSquadIdNotFound)
    end
  end
  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
